In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from catalyst import dl, utils
from ruwordnet.ruwordnet_reader import RuWordnet
import fasttext

ModuleNotFoundError: No module named 'ruwordnet'

In [4]:
cd baselines/

/home/x11dpg-qt/Projects/nlp/taxonomy-enrichment/baselines


In [7]:
ft = fasttext.load_model(path="models/baseline/cc.ru.300.bin")

In [67]:
class DSSM(nn.Module):
    def __init__(self):
        super(DSSM, self).__init__()
        self.eps = 0.0001
        self.encoder_query = nn.Sequential(
            nn.Linear(in_features=300, out_features=64),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(),
            nn.nn.Linear(in_features=64, out_features=32),
        )
        self.encoder_answer = nn.Sequential(
            nn.Linear(in_features=300, out_features=64),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(),
            nn.nn.Linear(in_features=64, out_features=32),
        )
    def forward(self, x, y):
        x = self.encoder_query(x)
        y = self.encoder_answer(y)
        return (torch.cosine_similarity(x, y) + 1) / (2 + self.eps)

In [77]:
config = {"db_path": "../data/ruwordnet.db",
    "ruwordnet_path": "../data/ruwordnet/",}
ruwordnet = RuWordnet(db_path=config["db_path"], ruwordnet_path=config["ruwordnet_path"], with_lemmas=False)

In [101]:
from collections import defaultdict
noun_synsets = defaultdict(list)
verb_synsets = defaultdict(list)
for sense_id, synset_id, text in ruwordnet.get_all_senses():
    if synset_id.endswith("N"):
        noun_synsets[synset_id].append(text.lower())
    elif synset_id.endswith("V"):
        verb_synsets[synset_id].append(text.lower())

In [ ]:
train = list()
for synset_id, list_text in noun_synsets.items():
    for text in list_text:
        query_vector = ft.get_sentence_vector(text)
        for hyper_synset_id in ruwordnet.get_hyponyms_by_id(synset_id):
            answer_vector = ft.get_sentence_vector(ruwordnet.get_name_by_id(synset_id=hyper_synset_id).lower())
            train.append((query_vector, answer_vector, 1))
            for hyper_hyper_synset_id in ruwordnet.get_hyponyms_by_id(hyper_synset_id):
                answer_vector = ft.get_sentence_vector(ruwordnet.get_name_by_id(synset_id=hyper_hyper_synset_id).lower())
                train.append((query_vector, answer_vector, 1))
                ruwordnet.
    else:
        for 
    

In [105]:
ruwordnet.get_hyponyms_by_id('7331-N')

['5792-N']

In [108]:
ruwordnet.get_hypernyms_by_id("4894-N")

['637-N']

In [109]:
ruwordnet.get_name_by_id('637-N')

'ПРЕСТУПЛЕНИЕ'

In [107]:
ruwordnet.get_name_by_id('107592-N')

'НАРУШЕНИЕ ПРАВИЛ'

In [118]:
fs['НАРУШЕНИЕ ПРАВИЛ'.lower()]

array([ 2.13473779e-03, -2.09583174e-02,  1.48383714e-02,  2.82679219e-02,
        2.35937219e-02, -3.20365932e-03, -3.20500210e-02, -1.07870856e-02,
        7.40950927e-03,  1.07754953e-03, -4.98748523e-05,  2.59401719e-03,
       -4.03801631e-03,  2.07881425e-02,  1.64431464e-02, -2.08233092e-02,
        2.15188786e-02,  2.99334410e-03, -1.38981948e-02, -1.83216594e-02,
        9.04623047e-03,  2.92443410e-02, -2.33816933e-02,  9.88289528e-03,
       -5.15789911e-03,  3.05191823e-03, -1.32673513e-02, -9.23410803e-03,
        1.51999928e-02, -2.36355849e-02,  8.25610291e-03, -2.22306289e-02,
        3.29165079e-04, -1.24075431e-02,  3.09189223e-02, -2.51840297e-02,
        2.51651071e-02, -1.02470266e-02,  5.63183352e-02,  7.72900507e-03,
       -1.55543881e-02, -2.06481619e-03,  8.24413728e-03,  5.27650081e-02,
       -2.13889964e-02,  1.28476033e-02,  6.80988189e-03, -9.17938724e-03,
       -1.94745837e-03,  2.19347682e-02,  9.18734353e-03, -2.80865952e-02,
       -4.79490217e-03,  

In [102]:
noun_synsets

defaultdict(list,
            {'147272-N': ['крестный родитель'],
             '7331-N': ['злоупотребления в торговле',
              'нарушение правил продажи',
              'нарушение правил торговли',
              'несоблюдение правил торговли'],
             '133812-N': ['водозабор', 'забор воды'],
             '106097-N': ['французский язык'],
             '132584-N': ['мембрана'],
             '135214-N': ['тактические действия',
              'тактический прием',
              'тактический ход',
              'тактика'],
             '9924-N': ['горизбирком', 'городская избирательная комиссия'],
             '104770-N': ['танганьика'],
             '132615-N': ['мерзлость'],
             '112039-N': ['улыбка', 'улыбочка'],
             '7793-N': ['подведомственность',
              'подведомственность судам',
              'подведомственность дел',
              'судебная подведомственность',
              'судебная юрисдикция',
              'юрисдикция суда',
              '

In [91]:
ruwordnet.get_all_ids()

['1-A',
 '1-N',
 '10-A',
 '10-N',
 '100-A',
 '100-N',
 '100006-N',
 '100007-A',
 '100007-N',
 '100008-A',
 '100008-N',
 '100009-N',
 '10001-N',
 '100013-A',
 '100013-N',
 '100022-A',
 '100022-N',
 '100028-A',
 '100028-N',
 '100029-N',
 '10003-N',
 '100030-N',
 '100036-N',
 '100037-N',
 '100038-N',
 '100039-A',
 '100039-N',
 '10004-N',
 '100040-A',
 '100040-N',
 '100042-A',
 '100042-N',
 '100043-A',
 '100043-N',
 '100046-A',
 '100046-N',
 '100048-N',
 '100049-A',
 '100049-N',
 '10005-A',
 '10005-N',
 '100050-N',
 '100053-N',
 '100054-N',
 '100055-N',
 '100056-N',
 '100057-N',
 '100058-N',
 '100060-N',
 '100061-A',
 '100061-N',
 '100062-A',
 '100062-N',
 '100063-A',
 '100063-N',
 '100064-A',
 '100064-N',
 '100066-N',
 '100070-A',
 '100070-N',
 '100076-N',
 '100077-N',
 '100078-A',
 '100078-N',
 '100079-A',
 '100079-N',
 '10008-A',
 '10008-N',
 '10008-V',
 '100083-N',
 '100086-N',
 '100089-A',
 '100089-N',
 '100091-N',
 '100095-A',
 '100095-N',
 '100097-A',
 '100097-N',
 '100098-N',
 '100

In [ ]:
# sample data
num_samples, num_features, num_classes = int(1e4), int(1e1), 4
X = torch.rand(num_samples, num_features)
y = (torch.rand(num_samples, ) * num_classes).to(torch.int64)

# pytorch loaders
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=32, num_workers=1)
loaders = {"train": loader, "valid": loader}

# device (TPU > GPU > CPU)
device = utils.get_device()  # <--------- TPU device

# model, criterion, optimizer, scheduler
model = torch.nn.Linear(num_features, num_classes).to(device)
criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters())

# model training
runner = dl.SupervisedRunner(device=device)
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    loaders=loaders,
    logdir="./logdir",
    num_epochs=3,
    callbacks=[dl.AccuracyCallback(num_classes=num_classes)]
)

In [1]:
from gensim import models

In [23]:
w2v = models.KeyedVectors.load('baselines/models/rusvec/187/model.model')

In [10]:
ft = models.word2vec.Word2Vec.load_word2vec_format('baselines/models/rusvec/probl/model.bin') #unicode_errors='ignore'

DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.

In [12]:
w2v = models.KeyedVectors.load_word2vec_format('baselines/models/rusvec/probl/model.bin', binary=True)

In [26]:
w2v.similar_by_word('яблоко')

[('яблокотец', 0.8306597471237183),
 ('яблочко', 0.8140920400619507),
 ('яблочок', 0.7795528173446655),
 ('яблочком', 0.7697737216949463),
 ('яблочка', 0.7608486413955688),
 ('яблочно', 0.7274317145347595),
 ('апельсин', 0.7031195163726807),
 ('яблони', 0.6989597082138062),
 ('яблоков', 0.6885384917259216),
 ('яблуко', 0.6746107339859009)]

In [31]:
w2v.similar_by_vector(w2v.get_vector('фрукты')-w2v.get_vector('яблоко'))

[('времяпрепровожденить', 0.4121701121330261),
 ('времяпрепровождение', 0.3883957862854004),
 ('препровождать', 0.38220521807670593),
 ('препровождение', 0.3817681670188904),
 ('времяпровождение', 0.3726576566696167),
 ('увеселительный', 0.3705158233642578),
 ('развлечение', 0.34749293327331543),
 ('прислуживание', 0.3445281386375427),
 ('обслуживание', 0.34109240770339966),
 ('предстоявать', 0.3386986553668976)]

In [ ]:
w2v()

In [33]:
w2v.similar_by_vector(w2v.get_vector('яблоко')-w2v.get_vector('прислуживание'))

[('яблоко', 0.8518052101135254),
 ('яблокотец', 0.7509956359863281),
 ('яблочко', 0.7494028806686401),
 ('яблочок', 0.7171580791473389),
 ('яблочка', 0.7079555988311768),
 ('яблочком', 0.7006387114524841),
 ('яблочно', 0.6716187000274658),
 ('яблонька', 0.6694883108139038),
 ('вишня', 0.6361050605773926),
 ('дынька', 0.6185712814331055)]

In [42]:
w2v.similar_by_vector((w2v.get_vector('фрукт')- w2v.get_vector('яблоко')))

[('фрукт', 0.5868464112281799),
 ('морепродукт', 0.5317202210426331),
 ('продукт', 0.49733683466911316),
 ('субпродукт', 0.4810965657234192),
 ('мясопродукт', 0.4787590801715851),
 ('ассортимент', 0.4622401297092438),
 ('специя', 0.4593478739261627),
 ('фруктовой', 0.4591425061225891),
 ('овощ', 0.45855236053466797),
 ('фруктово-ягодный', 0.45542579889297485)]

In [44]:
w2v.similar_by_vector(w2v.get_vector('фрукт'))

[('фрукт', 1.0),
 ('сухофрукт', 0.8410314321517944),
 ('фруктоз', 0.8078713417053223),
 ('овощ', 0.8030681610107422),
 ('фруктоза', 0.7922186851501465),
 ('сухофрукты', 0.7532907724380493),
 ('апельсин', 0.7011499404907227),
 ('овощи', 0.6743505001068115),
 ('ананас', 0.6638270616531372),
 ('морепродукт', 0.6634196639060974)]

array([ 0.24791238,  1.1697108 ,  1.0486867 ,  2.4460766 ,  0.4092201 ,
       -2.2370226 ,  2.7892332 , -0.5413557 , -3.0401971 ,  4.3648148 ,
        2.5491953 , -3.6986935 ,  1.8143531 ,  0.01234075,  0.79096353,
        0.72458047,  1.4402593 ,  0.37742156,  0.8345035 , -3.2912068 ,
        0.0423054 , -0.88803893, -0.4680734 , -1.0694517 ,  0.83508813,
        3.0716956 ,  2.482872  ,  3.3989656 ,  2.2645013 ,  0.7306646 ,
        1.0026728 ,  5.2052546 ,  3.4809494 ,  2.37288   , -1.1106567 ,
        1.3968848 , -2.8532267 , -0.64647937,  1.7402452 ,  0.07019034,
       -1.2752656 ,  3.1690695 ,  3.1242883 , -2.4793112 ,  5.056237  ,
        1.9257238 , -3.8036242 ,  0.34979945, -2.433759  , -0.11714642,
       -2.5351818 , -1.2661374 ,  1.3460566 ,  2.762393  , -2.6461983 ,
       -0.47741714, -0.05208785,  2.889596  ,  0.05937501,  2.695638  ,
       -1.5635235 ,  2.95846   , -2.426163  ,  2.28046   ,  2.8815947 ,
       -1.2443702 ,  0.9732161 ,  1.8850614 , -2.3006275 , -3.48

array([ 2.61061192e-01, -4.91336852e-01, -3.60842347e-01,  8.57962847e-01,
        1.29333687e+00, -2.09588766e+00,  1.01154089e+00,  6.74843490e-01,
        2.79797107e-01,  5.27385426e+00,  1.42682046e-01, -2.28006148e+00,
        9.83694434e-01,  1.08664382e+00, -3.51362526e-01, -3.27130556e-02,
        1.21597028e+00,  1.93990648e+00,  1.75211966e+00, -3.11251640e+00,
        2.23115635e+00, -3.19439816e+00,  2.77544677e-01,  1.02144098e+00,
        1.30024433e+00,  6.75924540e-01,  1.01811677e-01,  2.19220385e-01,
       -2.64993668e-01, -1.12090743e+00, -7.74099112e-01,  1.52088308e+00,
        4.96243048e+00,  8.09505582e-01, -3.36067104e+00,  2.46057725e+00,
        3.35251957e-01, -1.00126266e-02, -3.51568550e-01, -1.02401781e+00,
        8.89228821e-01,  6.66677594e-01, -6.21279538e-01, -3.39947534e+00,
        1.67794466e+00, -2.74425298e-01, -2.36090827e+00,  1.58411002e+00,
       -6.27985001e-01,  6.80009723e-01, -7.44284928e-01, -2.86829424e+00,
        2.36980245e-01,  

In [48]:
import scipy as sc


In [50]:
l = sc.stats.linregress(x=w2v.get_vector('яблоко'), y=w2v.get_vector('фрукт'))

In [51]:
p = l.slope *w2v.get_vector('огурец')  + l.intercept

In [53]:
w2v.similar_by_vector(p)

[('огурец', 0.999544620513916),
 ('огурца', 0.8400917053222656),
 ('огурчик', 0.8374102711677551),
 ('помидор', 0.7880475521087646),
 ('огуречик', 0.7835592031478882),
 ('огурчиком', 0.7568339109420776),
 ('помидорка', 0.7482763528823853),
 ('капуста', 0.7394626140594482),
 ('помидорк', 0.7304747104644775),
 ('помидорчик', 0.730029821395874)]

In [54]:
a = w2v.get_vector('яблоко')
b = w2v.get_vector('фрукт')

In [58]:
w2v.similarity('яблоко', "фрукт")

0.5716151

In [64]:
sum(a*b)/(sum(a**2)*sum(b**2))**(1/2)

0.5716151131934856